### ISSUE TITLE
Client shows connectionFailed state when server goes away

### ISSUE THREAD

**Issue by prspn** [PADL/SwiftOCA#11]
The client currently shows `Ocp1ConnectionState.connectionFailed` when the server goes away, and is not indicating  that it is trying to reconnect, instead going directly to `Ocp1ConnectionState.connected` when succeeding.

Should the client perhaps show `Ocp1ConnectionState.reconnecting` instead, and ultimately `Ocp1ConnectionState.connectionFailed` after giving up?

**Comment by lhoward** [comment]
65dc953f84cf974837a722140764d10c397ad988 avoids passing through the disconnected state when reconnecting, does this resolve it?

**Comment by prspn** [comment]
It appears to be resolved!
